### ISSUE TITLE
Git integration to record experiment commit hashes

### ISSUE THREAD

**Issue by geoffxy** [geoffxy/conductor#15]
We should integrate with Git to record experiment commit hashes. This integration will also be useful down the road for other features related to a repository's state. The Git integration should degrade gracefully if the user is not using Git in their project.

- [x] Python utility class for interfacing with git (#43)
- [x] Modify version index persistent format to support commit hash tracking
- [x] Configuration option to disable git tracking (#46)
- [x] Graceful fallback when the Conductor project is not tracked using git (#45)
- [x] Record commit hash when running an experiment (#45)
- [x] Experiment version selection using closest commit ancestor (#45)

**Comment by geoffxy** [comment]
Completed as part of
- #43
- #45
- #46
